# Generated by Django 4.2.7 on 2023-11-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="pdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(null=True, upload_to="")),
            ],
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
