# Generated by Django 4.2.7 on 2023-11-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0002_pdf_delete_uploadedfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="pdf_file",
            field=models.FileField(null=True, upload_to="pdf_files/"),
        ),
    ]
